services:
  # Backend service - Node.js + Tesseract OCR
  backend:
    build: ./backend
    container_name: ocr-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - LLAMA_API_URL=http://host.docker.internal:11434/api/generate
      - LLAMA_MODEL=llama3.2:3b
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service - React + Nginx
  frontend:
    build: ./frontend
    container_name: ocr-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

# Networks
networks:
  default:
    name: ocr-network
